name: CI

on:
  push:
    
  workflow_dispatch:  

jobs:

  build-ubuntu:
    
    runs-on: ubuntu-latest
    
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip action]')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$GITHUB_WORKSPACE"
        
      - name: Retrieve versions.properties
        run: |
          wget -q https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties
          
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java

      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala

      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
          
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          bin/build.cmd test

  build-mac:
    
    runs-on: macOS-latest
    
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip action]')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$GITHUB_WORKSPACE"
        
      - name: Retrieve versions.properties
        run: |
          curl -JLOs https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties
          
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/mac/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java

      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala

      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier

      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          bin/build.cmd test

  build-windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip action]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$($env:GITHUB_WORKSPACE)"
      - name: Install Cygwin
        shell: cmd
        run: |
          choco config get cacheLocation
          choco install --no-progress cygwin
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P mingw64-x86_64-gcc-core,mingw64-x86_64-gcc-g++,make,cmake
      - name: Retrieve versions.properties
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties" -OutFile "versions.properties"
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\bin\win\java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\bin\scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}\cache\coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Test
        shell: cmd
        run: |
          set COURSIER_CACHE=%GITHUB_WORKSPACE%\cache\coursier
          set PATH=C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin;%PATH%
          set CC=x86_64-w64-mingw32-gcc.exe
          set CXX=x86_64-w64-mingw32-c++.exe
          cd /d %GITHUB_WORKSPACE%
          git submodule update --init --recursive
          bin\build.cmd test
          
  skip:
    
    runs-on: ubuntu-latest
    
    if: "contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip action]')"
    
    steps:
      - run: |
          echo Skipped
