name: CI

on:
  push:
    
  workflow_dispatch:  

jobs:

  build-ubuntu:
    
    runs-on: ubuntu-latest
    
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip action]')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$GITHUB_WORKSPACE"
        
      - name: Retrieve versions.properties
        run: |
          wget -q https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties
          
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java

      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala

      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v1
        with:
          path: ${{ env.workspace }}/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
          
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          bin/build.cmd test
